CREATE DATABASE IF NOT EXISTS appnode;
USE appnode;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  city VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER 'joao'@'localhost' IDENTIFIED BY '12345678';

GRANT ALL PRIVILEGES ON appnode.* TO 'joao'@'localhost';